[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  UMI_APP_DEMO_MODE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
